name: "Pull Request Docs Check"

on: 
  pull_request:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Create the new documentation
      uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "python -m pip install pip sphinx_rtd_theme numpy scipy GPy matplotlib -U"
        docs-folder: "docs/"

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
